### ISSUE TITLE
Travis build status is no longer posting back to the PR

### ISSUE THREAD

**Issue by brettgoss** [sendwithus/vic-startup-jobs#234]
On recent PR's, I noticed that the build status isn't being posted back to the PR any longer. The PR is still kicking off a build in Travis, as evidenced [here](https://travis-ci.org/github/sendwithus/vic-startup-jobs/builds/735495466), however [the corresponding PR](https://github.com/sendwithus/vic-startup-jobs/pull/233) doesn't have any indication that the build was run, whether it failed or passed.

I did some digging and I suspect that we might be using the legacy Github Services integration rather than Github Apps, but someone with repository admin would need to confirm. If we are in fact on legacy, we can migrate to Github Apps following this guide: https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/

**Comment by alannadare** [comment]
Hey @brettgoss is this resolved with some of the more recent commits? Thanks!

**Comment by brettgoss** [comment]
Hey @alannadare unfortunately not. [My latest PR](https://github.com/sendwithus/vic-startup-jobs/pull/240) didn't have the build status posted on it, whereas [one of my PR's back in July](https://github.com/sendwithus/vic-startup-jobs/pull/223) shows the build status on the commit.

It looks like it stopped working in early August of 2020 
![image](https://user-images.githubusercontent.com/1578328/104787054-6989dc80-5743-11eb-8b01-381e0a8f98f2.png)

**Comment by dlsteuer** [comment]
@brettgoss I just did the migration now and it appears to be working. So I'm going to close this issue now. See #254

**Comment by brettgoss** [comment]
@dlsteuer Awesome, thanks for that!
