### ISSUE TITLE
Rename the default branch

### ISSUE THREAD

**Issue by pzelnip** [sendwithus/vic-startup-jobs#266]
In the last couple years in industry there has been movement away from the original default branch in Git called `master` to something more culturally sensitive (such as `main`, `mainline`, `default`, etc).

I noticed this repo still uses the old default branch name, would it be possible to change it to something more culturally sensitive?

**Comment by demoore** [comment]
The change to `main` went live a couple weeks back! :eyes: Please keep making issues for stuff like this. :smile:
